name: CI Build - Android
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: Internal distribution build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Dependencies
        run: npm ci 
      - name: Run EAS build
        run: eas build --platform android --profile preview --non-interactive